### ISSUE TITLE
sm.ms  图床 显示用户名字段缺失 但是没办法设置用户名

### ISSUE THREAD

**Issue by kihlh** [up2b/up2b#15]
invalid args `config` for command `update_config`: missing field `username`

环境
win10  x64   版本 v0.3.0-alpha.1
安装路径默认  进程有管理员权限

![image](https://github.com/thep0y/up2b-rs/assets/62889891/f9330168-a9c8-4f02-89e2-35eab16b9116)

**Comment by thep0y** [comment]
是否安装并配置过 0.2.0 版本？
